baseurl = "https://purduesocet.github.io/"
languageCode = "en-us"
title = "Purdue SoCet"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

publishdir = "../"

[params]
	# General information
	author = "PurdueSoCet"
	description = "Purdue System-On-Chip Extension Technologies"
	copyright = "Released under the MIT license"

	# Repository - This adds gross download buttons
	#provider = "GitHub"
	#repo_url = "https://github.com/PurdueSoCet"

	#version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "gold"
    	accent  = "black"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
#	twitter = ""
	github  = "PurdueSoCet"
#	email   = "hello@email.com"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Projects"
	url    = "projects/"
	weight = 10

[[menu.main]]
	name   = "System-On-Chips"
	url    = "system-on-chips/"
	weight = 20

[[menu.main]]
	name   = "Papers"
	url    = "papers/"
	weight = 30

[[menu.main]]
	name   = "Team"
	url    = "team/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
